/**:
  ros__parameters:
    topic_names:
      - /sensing/lidar/front_left/pointcloud_before_sync
      - /sensing/lidar/front_right/pointcloud_before_sync
      - /sensing/lidar/side_left/pointcloud_before_sync
      - /sensing/lidar/side_right/pointcloud_before_sync
      - /sensing/lidar/rear/pointcloud_before_sync
    frame_ids:
      - hesai_front_left
      - hesai_front_right
      - hesai_side_left
      - hesai_side_right
      - hesai_rear
    rate_hz: 10.0
