/**:
  ros__parameters:
    diagnostics:
      functional_safety:
        mode: advanced
        error_definitions_path: $(find-pkg-share autoware_launch)/config/sensing/lidar/diagnostics/ot218_fusa_codes.csv
        ignored_error_codes:
          - 0x1011 # Already ensured by SYNC.TOOLING
